version: "3"
services:



  backend:
    build: /backend
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db_aplhaMinicommerce
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=mh8q23pr99
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      #- api.security.token.secret=${JWT_SECRET:28764JY723ffZ}
    depends_on:
      - database
    restart: on-failure


  database:
    image: 'postgres'
    environment:
      - 'POSTGRES_DB=db_aplhaMinicommerce'
      - 'POSTGRES_PASSWORD=mh8q23pr99'
      - 'POSTGRES_USER=admin'
    ports:
      - 5432:5432
    volumes:
      - /app/database/postgre 


  frontend:
    build: /frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: on-failure
  
    
    